[custom]
;解决DNS泄露，无分流群组
# 自定义直连规则
ruleset=🚀 节点选择,[]DOMAIN,test12345678.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,imgse.com

ruleset=DIRECT,[]DOMAIN,0.openwrt.pool.ntp.org
ruleset=DIRECT,[]DOMAIN,0.cn.pool.ntp.org
ruleset=DIRECT,[]DOMAIN,mq.tineco.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,oray.net
ruleset=DIRECT,[]DOMAIN-SUFFIX,oray.com
ruleset=DIRECT,[]DOMAIN,client-api-v2.oray.com
ruleset=DIRECT,[]DOMAIN,client-api.oray.com
ruleset=DIRECT,[]DOMAIN,upload-cdn.orayimg.com
ruleset=DIRECT,[]DOMAIN,rc10-g2.oray.com
ruleset=DIRECT,[]DOMAIN,dw.oray.com
ruleset=DIRECT,[]DOMAIN,api-std.sunlogin.oray.com
ruleset=DIRECT,[]DOMAIN,cdn.orayimg.com
ruleset=DIRECT,[]DOMAIN,user-api-v2.oray.com
ruleset=DIRECT,[]DOMAIN,sl-tk.oray.com
ruleset=DIRECT,[]DOMAIN,ws-std01.sunlogin.oray.com
ruleset=DIRECT,[]DOMAIN,ws-std06.sunlogin.oray.com
ruleset=DIRECT,[]DOMAIN,ws-std03.sunlogin.oray.com
ruleset=DIRECT,[]DOMAIN,sl-log.oray.net
ruleset=DIRECT,[]DOMAIN,sunlogin.oray.com
ruleset=DIRECT,[]DOMAIN,res.orayimg.com
ruleset=DIRECT,[]DOMAIN,webapi.sunlogin.oray.com
ruleset=DIRECT,[]DOMAIN,sentry.oray.com
ruleset=DIRECT,[]DOMAIN,tk.oray.com
ruleset=DIRECT,[]DOMAIN,api-ti.sunlogin.oray.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,ludashi.com
ruleset=DIRECT,[]DOMAIN,s.ludashi.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,todesk.com
ruleset=DIRECT,[]DOMAIN,st.todesk.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,kaadas.com
ruleset=DIRECT,[]DOMAIN,kaadas.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,tencentcs.com
ruleset=DIRECT,[]DOMAIN,ap-guangzhou.cls.tencentcs.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,narwaltech.com
ruleset=DIRECT,[]DOMAIN,robot.narwaltech.com

ruleset=DIRECT,[]DOMAIN,kuaishou.httpdns.pro

ruleset=DIRECT,[]DOMAIN,api.cn.xmitech.net
ruleset=DIRECT,[]DOMAIN,mqtt.cn.xmitech.net

ruleset=DIRECT,[]DOMAIN-SUFFIX,smartmidea.net
ruleset=DIRECT,[]DOMAIN-SUFFIX,midea.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,alibabachengdun.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,aliyundrive.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,alipan.com
ruleset=DIRECT,[]DOMAIN,aone.alibaba-inc.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,ecouser.net
ruleset=DIRECT,[]DOMAIN-SUFFIX,echatsoft.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,narwal.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,pddpic.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,wifishenqi.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,livecdn.annuoxun.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,juziwulian.com

ruleset=DIRECT,[]DOMAIN,public.gdtimg.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,tcdnos.com

ruleset=DIRECT,[]DOMAIN,down.anticheatexpert.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,leigod.com
ruleset=DIRECT,[]DOMAIN,leigod.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,gamepp.com
ruleset=DIRECT,[]DOMAIN,valid.gamepp.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,nn.com
ruleset=DIRECT,[]DOMAIN,leigod.nn.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,liuhaba.com

ruleset=DIRECT,[]DOMAIN,sdk.yunkaino1.com

ruleset=DIRECT,[]DOMAIN,time.android.com

ruleset=DIRECT,[]DOMAIN,ops.gx.nvidia.com

ruleset=DIRECT,[]DOMAIN,client.wns.windows.com

ruleset=DIRECT,[]DOMAIN-SUFFIX,rustdesk.com
ruleset=DIRECT,[]DOMAIN,rs-ny.rustdesk.com
ruleset=DIRECT,[]DOMAIN,ovh-fr1.rustdesk.com

# NCSoft / 天堂W / 紫P
ruleset=DIRECT,[]DOMAIN,up4svr.plaync.com.tw
ruleset=DIRECT,[]DOMAIN,api.g.nc.com
ruleset=DIRECT,[]DOMAIN,mobileappconfig.g.nc.com
ruleset=DIRECT,[]DOMAIN,cli.g.nc.com
ruleset=DIRECT,[]DOMAIN,assets.playnccdn.com
ruleset=DIRECT,[]DOMAIN,purple-store.plaync.com
ruleset=DIRECT,[]DOMAIN,fizz-download.playnccdn.com
ruleset=DIRECT,[]DOMAIN,gs-purple.ncupdate.com
ruleset=DIRECT,[]DOMAIN,noti.plaync.com
ruleset=DIRECT,[]DOMAIN,jam-static.plaync.com
ruleset=DIRECT,[]DOMAIN,api-community.plaync.com
ruleset=DIRECT,[]DOMAIN,purple-talk.plaync.com
ruleset=DIRECT,[]DOMAIN,lime-api.global.plaync.com
ruleset=DIRECT,[]DOMAIN,nccr-api.global.nc.com
ruleset=DIRECT,[]DOMAIN,purple-pub.global.plaync.com
ruleset=DIRECT,[]DOMAIN,gs-purple.download.ncupdate.com
ruleset=DIRECT,[]DOMAIN,lagavulin.ncsoft.com
ruleset=DIRECT,[]DOMAIN,mgr.gameguard.co.kr
ruleset=DIRECT,[]DOMAIN,nprotect-cdn.plaync.com.tw
ruleset=DIRECT,[]DOMAIN,lime-l2m-api.plaync.com
ruleset=DIRECT,[]DOMAIN,mtw-l2m-win.cdn.plaync.com.tw
ruleset=DIRECT,[]DOMAIN,d8pektcc48.execute-api.ap-northeast-2.amazonaws.com
ruleset=DIRECT,[]DOMAIN,www.gameguard.co.kr

ruleset=DIRECT,[]DOMAIN-SUFFIX,plaync.com.tw
ruleset=DIRECT,[]DOMAIN-SUFFIX,plaync.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,playnccdn.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,nc.com

# Deskin
ruleset=DIRECT,[]DOMAIN,st.deskin.io
ruleset=DIRECT,[]DOMAIN,users.deskin.sg
ruleset=DIRECT,[]DOMAIN,api.deskin.io
ruleset=DIRECT,[]DOMAIN,deskin.us-ca.ufileos.com
ruleset=DIRECT,[]DOMAIN-SUFFIX,deskin.io
ruleset=DIRECT,[]DOMAIN-SUFFIX,deskin.sg

# AnyViewer
ruleset=DIRECT,[]DOMAIN,controlserver.anyviewer.com

# 傲梅
ruleset=DIRECT,[]DOMAIN,www2.aomeisoftware.com
ruleset=DIRECT,[]DOMAIN,a.aomeisoftware.com

# 其它
ruleset=DIRECT,[]DOMAIN,ll.bdzybf11.com
ruleset=DIRECT,[]DOMAIN,www.ex-liema.com

# 自定义直连 IP

ruleset=DIRECT,[]IP-CIDR,210.61.114.0/24,no-resolve
ruleset=DIRECT,[]IP-CIDR,210.242.186.0/24,no-resolve
ruleset=DIRECT,[]IP-CIDR,5.5.5.5/32,no-resolve
ruleset=DIRECT,[]IP-CIDR,129.227.70.0/24,no-resolve
ruleset=DIRECT,[]IP-CIDR,2.59.218.0/24,no-resolve



# 自定义代理规则
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,googlevideo.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,nodeseek.com



#ruleset=📢 mosdns代理,[]PROCESS-NAME,mosdns
#ruleset=REJECT,[]DOMAIN-SUFFIX,android-appboot.netflix.com
#ruleset=REJECT,[]DOMAIN-SUFFIX,android.prod.cloud.netflix.com
#ruleset=REJECT,[]DOMAIN-SUFFIX,appboot.netflix.com
#ruleset=REJECT,[]DOMAIN-SUFFIX,ios.prod.cloud.netflix.com
#ruleset=REJECT,[]DOMAIN-SUFFIX,ios.ngp.prod.cloud.netflix.com
#ruleset=REJECT,[]DOMAIN-SUFFIX,nrdp.prod.cloud.netflix.com
#ruleset=REJECT,[]DOMAIN-SUFFIX,nrdp-ipv6.prod.ftl.netflix.com
#ruleset=REJECT,[]DOMAIN-SUFFIX,nrdp80-appboot.netflix.coma
#ruleset=REJECT,[]DOMAIN-SUFFIX,nrdp.ws.ale.netflix.com
#ruleset=REJECT,[]IP-CIDR,8.8.8.8/32,no-resolve
#ruleset=REJECT,[]IP-CIDR,8.8.4.4/32,no-resolve
#ruleset=🎥 Netflix,[]PROCESS-NAME,mosdns




ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
#ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
# 内容：中国IP地址段ipv4
# ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=📢 GoogleAll`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=✨ OpenAI`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=👯‍♂️ TikTok`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=🎥 Netflix`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=🎥 HBOMAX`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=🐹 DisneyPlus`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=📹 Youtube`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=🙋 Telegram`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=Ⓜ️ 微软`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=😀 Instagram`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
#custom_proxy_group=📢 mosdns代理`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
#custom_proxy_group=🚀 dns解析`select`[]♻️ 自动选择`[]🚀 节点选择`[]DIRECT`.*

enable_rule_generator=true
overwrite_original_rules=true
